# Generated by Django 2.2.6 on 2019-10-21 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('lectureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Lecture')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.User')),
            ],
        ),
    ]
